// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

interface CssExports {
  'Task__edit-button': string;
  'Task__edit-button_hidden': string;
  'Task__edit-icon_size_sm': string;
  'Task__persona': string;
  'Task__persona_size_sm': string;
  'Task__persona_theme_primary': string;
}
const cssExports: CssExports;
export default cssExports;
