// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

interface CssExports {
  'folderCount': string;
  'folderFront': string;
  'folderIcon': string;
  'folderList': string;
  'folderPaper': string;
  'folderTile': string;
  'folderTileContent': string;
  'folderTileName': string;
  'folderTileNamePlate': string;
  'folderTileNameText': string;
  'imageList': string;
  'imagesGalleryWebpart': string;
  'overlay': string;
  'pager': string;
  'pagerText': string;
}
const cssExports: CssExports;
export default cssExports;
