// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

interface CssExports {
  'button_status_cancelled': string;
  'button_status_finished': string;
  'button_status_open': string;
  'button_status_pending': string;
  'cancelled': string;
  'finished': string;
  'pending': string;
}
const cssExports: CssExports;
export default cssExports;
