// This file is automatically generated.
// Please do not change this file!

/* tslint:disable */
/* eslint-disable */

interface CssExports {
  'Task__remark-icon': string;
  'Task__title': string;
  'Task_person': string;
  'body': string;
  'expired': string;
  'header': string;
  'hours': string;
  'separator': string;
  'status': string;
  'subheader': string;
  'task': string;
}
const cssExports: CssExports;
export default cssExports;
