"use strict";
// This file is automatically generated.
// Please do not change this file!
Object.defineProperty(exports, "__esModule", { value: true });
var cssExports = {};
exports.default = cssExports;
//# sourceMappingURL=CustomsCodeField.module.scss.js.map